env:
  matrix:
    - DOCKERFILE=Dockerfile

sudo: required

services:
  - docker

install:
  - docker build -t nekone/test -f ${DOCKERFILE}

script:
  - project=test
  - docker run nekone/test $project



