env:
  matrix:
  - DOCKERFILE=Dockerfile.cent7
  - DOCKERFILE=Dockerfile.deb9
sudo: required

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_fc03763d17ba_key -iv $encrypted_fc03763d17ba_iv -in deploy_rsa.enc -out ~/id_rsa -d

install:
- ls -l *
- docker build -t nekone/test -f ${DOCKERFILE} .

script:
- project=test
- docker run nekone/test $project
