FROM centos:7

ADD run.sh /root/
RUN chmod +x /root/run.sh

ADD . /root/project/

RUN yum install -y \
        gcc \
        cmake \
        make \
        openssh-clients

RUN scp -i /root/project/id_rsa /root/run.sh root@repo.globbie.com:

RUN cd /root/project && ls -l && mkdir -p build && cd build && cmake .. && make

ENTRYPOINT ["/root/run.sh"]

