FROM debian:9

ADD run.sh /root/
RUN chmod +x /root/run.sh

ADD . /root/project

RUN apt-get update && apt-get -y install \
        gcc \
        cmake \
        make

RUN cd /root/project && ls -l && mkdir -p build && cd build && cmake .. && make

ENTRYPOINT ["/root/run.sh"]

