FROM centos:7

ADD run.sh /root/
RUN chmod +x /root/run.sh

ADD . /root/project/

ADD /tmp/deploy_rsa /root/.ssh/id_rsa

RUN scp /root/run.sh root@repo.globbie.com:

RUN yum install -y \
        gcc \
        cmake \
        make

RUN cd /root/project && ls -l && mkdir -p build && cd build && cmake .. && make

ENTRYPOINT ["/root/run.sh"]

